os: osx
osx_image: xcode11.3

language: swift

cache:
  - Carthage/

before_install:
  - chmod +x scripts/complete_setup.sh

install:
  - sh scripts/complete_setup.sh

before_script:
  - chmod +x scripts/run_tests.sh

script:
  - sh scripts/run_tests.sh